
server:
  port: 8081
  servlet:
    context-path: /console/dbtransfer

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.242.140:7501/db_transfer?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=true
    username: root
    password: 2vKeG&1.3

  sql:
    init:
      schema-locations: classpath:db/schema-mysql.sql
      mode: always
      platform: mysql
      password: 2vKeG&1.3
      username: root


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

